import type { Detector } from './types.ts';

export function detectors(): Detector[] {
  return [
    {
      id: 'gitleaks.aws-access-key-id',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: '(?:A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}',
      confidence: 0.97,
    },
    {
      id: 'gitleaks.aws-secret-access-key',
      class: 'credentials.secret',
      mode: 'contains',
      pattern:
        '(?i)(?:aws_secret_access_key|aws[_-]?secret[_-]?key)\\s*[:=]\\s*[\'"]?[A-Za-z0-9/+=]{40}[\'"]?',
      confidence: 0.95,
    },
    {
      id: 'gitleaks.github-pat',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'ghp_[A-Za-z0-9_]{36}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.github-oauth',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'gho_[A-Za-z0-9_]{36}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.github-app-token',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'gh[us]_[A-Za-z0-9_]{36}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.github-refresh-token',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'ghr_[A-Za-z0-9_]{76}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.github-fine-grained-pat',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'github_pat_[A-Za-z0-9_]{82}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.gitlab-pat',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'glpat-[A-Za-z0-9\\-=_]{20,}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.gitlab-pipeline-trigger',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'glptt-[A-Za-z0-9\\-=_]{40}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.gitlab-runner-registration',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'GR1348941[A-Za-z0-9\\-_]{20,}',
      confidence: 0.97,
    },
    {
      id: 'gitleaks.slack-bot-token',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'xoxb-[0-9]{10,13}-[0-9]{10,13}-[a-zA-Z0-9]{24,}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.slack-user-token',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'xoxp-[0-9]{10,13}-[0-9]{10,13}-[0-9]{10,13}-[a-z0-9]{32}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.slack-app-token',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'xapp-[0-9]-[A-Z0-9]{11}-[0-9]{13}-[a-z0-9]{64}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.slack-webhook',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'https://hooks\\.slack\\.com/services/T[A-Z0-9]+/B[A-Z0-9]+/[A-Za-z0-9]+',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.stripe-live-key',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'sk_live_[0-9a-zA-Z]{24,}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.stripe-test-key',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'sk_test_[0-9a-zA-Z]{24,}',
      confidence: 0.95,
    },
    {
      id: 'gitleaks.google-api-key',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'AIza[0-9A-Za-z\\-_]{35}',
      confidence: 0.97,
    },
    {
      id: 'gitleaks.twilio-api-key',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'SK[0-9a-fA-F]{32}',
      confidence: 0.90,
    },
    {
      id: 'gitleaks.sendgrid-api-key',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'SG\\.[A-Za-z0-9\\-_]{22}\\.[A-Za-z0-9\\-_]{43}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.mailchimp-api-key',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: '[0-9a-f]{32}-us[0-9]{1,2}',
      confidence: 0.92,
    },
    {
      id: 'gitleaks.npm-token',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'npm_[A-Za-z0-9]{36}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.pypi-token',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'pypi-[A-Za-z0-9\\-_]{16,}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.private-key',
      class: 'credentials.secret',
      mode: 'contains',
      pattern:
        '-----BEGIN (?:RSA |EC |DSA |OPENSSH |PGP |ENCRYPTED )?PRIVATE KEY(?:\\sBLOCK)?-----',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.vault-token',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'hvs\\.[A-Za-z0-9_\\-]{24,}',
      confidence: 0.97,
    },
    {
      id: 'gitleaks.vault-batch-token',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'hvb\\.[A-Za-z0-9_\\-]{24,}',
      confidence: 0.97,
    },
    {
      id: 'gitleaks.terraform-token',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: '[a-z0-9]{14}\\.atlasv1\\.[a-z0-9\\-_=]{60,70}',
      confidence: 0.97,
    },
    {
      id: 'gitleaks.age-secret-key',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'AGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L]{58}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.doppler-token',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'dp\\.st\\.[a-z0-9\\-_]{43}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.shopify-access-token',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'shpat_[a-fA-F0-9]{32}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.shopify-custom-token',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'shpca_[a-fA-F0-9]{32}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.shopify-private-token',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'shppa_[a-fA-F0-9]{32}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.shopify-shared-secret',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'shpss_[a-fA-F0-9]{32}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.discord-bot-token',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: '(?:M|N|O)[A-Za-z0-9]{23,}\\.[A-Za-z0-9\\-_]{6}\\.[A-Za-z0-9\\-_]{27,}',
      confidence: 0.85,
    },
    {
      id: 'gitleaks.digitalocean-pat',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'dop_v1_[a-f0-9]{64}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.digitalocean-oauth',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'doo_v1_[a-f0-9]{64}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.digitalocean-refresh',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'dor_v1_[a-f0-9]{64}',
      confidence: 0.99,
    },
    {
      id: 'gitleaks.databricks-token',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: 'dapi[a-h0-9]{32}',
      confidence: 0.97,
    },
    {
      id: 'gitleaks.generic-api-key',
      class: 'credentials.secret',
      mode: 'contains',
      pattern:
        '(?i)(?:api_key|apikey|api-key|secret_key|secret-key|access_token|auth_token|client_secret)\\s*[:=]\\s*[\'"]?[A-Za-z0-9/+=._\\-]{20,}[\'"]?',
      confidence: 0.80,
    },
    {
      id: 'gitleaks.password-in-url',
      class: 'credentials.secret',
      mode: 'contains',
      pattern: '(?i)://[^/\\s:]+:[^/\\s@]{3,}@[^/\\s]+',
      confidence: 0.90,
    },
  ];
}
